apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-prepper.fullname" . }}-config
  labels:
    {{- include "data-prepper.labels" . | nindent 4 }}
data:
{{- range $configName, $configYaml := .Values.config }}
  {{ $configName }}: |
  {{- if eq (kindOf $configYaml) "map" }}
    {{- tpl (toYaml $configYaml) $ | nindent 4 }}
  {{- else }}
    {{- tpl $configYaml $ | nindent 4 -}}
  {{- end -}}
{{- end -}}
